// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_crawl2_TMBExports
#include <TMB.hpp>
#include ""

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
    error("Unknown model.");
  return 0;
}
